### ISSUE TITLE
Impact of config changes

### ISSUE THREAD

**Issue by Henry-E** [metaDAOproject/meta-dao-frontend#67]
Referring to all the smaller changes and PR listed here. https://hackmd.io/@HenryE/Bkvk6eG10#Autocrat

Not sure what UI changes are needed but just mentioning in case they do impact down the line
- Default pass threshold is now 3%
- TWAP observation change is $5 per slot now
- META lot sizes are now 0.1 META in openbook
- Because of the quote lot size change, price lots are different too now. So the TWAP represents the cost of 0.1 META and might need to be multiplied by 10x to get the true price per META.

**Comment by R-K-H** [comment]
Working on this https://github.com/metaDAOproject/meta-dao-frontend/pull/64
