### ISSUE TITLE
Configure proper Compute Limit for txns

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-frontend#68]
This is a stub, but has now been placed in the current UI just needs to be confirmed to be leveraged in the new UI.

**Comment by jshiohaha** [comment]
Ah cool, I'm curious to see how it works! I was also thinking about something similar during the transaction management task. My initial thinking was that you can we can offer 2 options to callers:

1. pass in a set value if they know what they want, or
2. not think about it and have us try to derive a custom value based on the transaction instructions. Although, this last option is definitely more complex and probably not needed for a first implementation.

**Comment by R-K-H** [comment]
> Ah cool, I'm curious to see how it works! I was also thinking about something similar during the transaction management task. My initial thinking was that you can we can offer 2 options to callers:
> 
> 1. pass in a set value if they know what they want, or
> 2. not think about it and have us try to derive a custom value based on the transaction instructions. Although, this last option is definitely more complex and probably not needed for a first implementation.

https://github.com/metaDAOproject/meta-dao-frontend/blob/3834f3fc04da22da446a9c395432e761a15f20b0/hooks/useTransactionSender.tsx#L42
