### ISSUE TITLE
Integrate Dialect into UI

### ISSUE THREAD

**Issue by metaproph3t** [metaDAOproject/meta-dao-frontend#69]
When I asked Kyle to boost MetaDAO, he asked us to integrate Dialect into the UI. So let's integrate Dialect!

**Comment by R-K-H** [comment]
Need to add another task to integrate this into the deploy / scripts... https://github.com/metaDAOproject/metadao-notifications
https://github.com/metaDAOproject/metadao-messaging/issues/1
